### ISSUE TITLE
Amazing !!! maybe a .exe?

### ISSUE THREAD

**Issue by Root-FTW** [DvorakDwarf/Infinite-Storage-Glitch#12]
wow, thanks for surprising the gitHub community with this project, at the time I write these lines of text, it is the #1 trending project on GitHub, I hope you can generate an .exe or at least a python version of this project :D

THX

**Comment by Kovinda** [comment]
> wow, thanks for surprising the gitHub community with this project, at the time I write these lines of text, it is the #1 trending project on GitHub, I hope you can generate an .exe or at least a python version of this project :D
> 
> THX

isg_4real.exe: PE32+ executable (console) **x86-64, for MS Windows**

[Download](https://mega.nz/file/Vso0TaZC#5BjNqLGpJRTXLT7Fx-QOzcNwTVg1L4ni36DvNEmRVhY)
[Virustotal](https://www.virustotal.com/gui/file/304c39204ce4bb3ef376af1f8c63f0d987d9c8f63add9ac9a1296d3443f99e71/detection)


isg_4real: ELF 64-bit LSB pie executable, **x86-64**, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=936cff2d58928c7dc53a4abb85bb1c724b4d0934, **for GNU/Linux 3.2.0**, with debug_info, not stripped

[Download](https://mega.nz/file/w4RQxKCT#xt1j81if-emFSi037aTLnc2BZG8qEEBsYzixwNanG0s)
[Virustotal](https://www.virustotal.com/gui/file/ed2f1251421cc3eb12762870b6168bb48cf6d88d638cbfd9bf2100dfc1f90e1f?nocache=1)

**Comment by MullerHub** [comment]
If there is an .exe in the future, please mark me here.
I probably compile and test it first, but a .exe would make it easier on windows.

**Comment by salman0ansari** [comment]
> isg_4real: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9ac95a0e636010d45d2b60df9838c275c12ac5c4, for GNU/Linux 4.4.0, with debug_info, not stripped

> sha1sum := 021ac4d75c2d19ccc0e7a3782a5e8ef9de1326f9

> https://www.virustotal.com/gui/file-analysis/OWRhYWJhYjczOWVkYjk2NGJjYzMyOTViZjBjZWJiMzY6MTY3NzEyOTEzMA==

https://mega.nz/file/uJQnGSzA#Himgs5carWdab-QfHBFo-1SL2O4Vk9AQCojTKfGxhd4

**Comment by zeromero-dev** [comment]
***Maintainers of the ISG do not recommend anyone download .exe files from anyone except on the GitHub release page!***
If you do - *you're doing it at your own risk.*

*For now* the only way to run it is to build it from source.

**Comment by Gaming32** [comment]
Just install Rust and run `cargo run --release`.
