### ISSUE TITLE
Bad cpu type in executable

### ISSUE THREAD

**Issue by dimcat** [DvorakDwarf/Infinite-Storage-Glitch#17]
i downloaded the executable on mac and its not working, am i an idot or??

**Comment by Gnomorian** [comment]
it is only for ARM.

if your cpu is intel or amd for example, your going to have to compile from source

**Comment by BasToTheMax** [comment]
Oof. How much ram and cpu cores are required to compile?

**Comment by zeromero-dev** [comment]
> Oof. How much ram and cpu cores are required to compile?

I've built it with 4 cores and 4GB ram on my VM and it was constantly 99% CPU and RAM usage for me.
It's more just so you don't do anything on pc while the thing builds.

**Comment by Blackmine57666** [comment]
I honestly don't know, I have 16 cores and 16go of ram and it was enough.
I compiled it on my fork, feel free to download it [here](https://github.com/Blackmine57666/Infinite-Storage-Glitch/releases/)

(I'm quite new to this, so please say if it does work on not)

**Comment by DvorakDwarf** [comment]
I still need to add the x86 executable when I can

**Comment by xiaotuzididi** [comment]
thankyou

**Comment by zeromero-dev** [comment]
Compile the project from source until the new executable is not released 🙂
