### ISSUE TITLE
Create a file system driver for the storage?

### ISSUE THREAD

**Issue by markusl** [DvorakDwarf/Infinite-Storage-Glitch#2]
For your next project, you might want to consider writing a file system driver where user could store / fetch files to and from a virtual file system which is backed by YouTube. Use playlists as file index or something like that :)

**Comment by DvorakDwarf** [comment]
I was hoping to do it in the future but it sounds like quite a bit of work

**Comment by gsmachado** [comment]
yes, quite some work... 😓 

check https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/4

**Comment by oOHiyoriOo** [comment]
> I was hoping to do it in the future but it sounds like quite a bit of work

sounds awesome haha, i would love to see this 😆
