### ISSUE TITLE
Audio too? 

### ISSUE THREAD

**Issue by ggppjj** [DvorakDwarf/Infinite-Storage-Glitch#20]
Seems like there's an additional storage medium here waiting to be explored in the audio tracks. Can surround sound be used for more individual tracks on a single video? I'd be interested in seeing just how much more data can be stored in the same amount of video.

**Comment by V037** [comment]
get real

**Comment by ggppjj** [comment]
@V037 I don't understand your request.

**Comment by cryptoquick** [comment]
The problem is the compression and degradations in bitrate, so some sort of forward error correction would be needed, which would reduce how much could be transmitted via audio. That said, these videos are trippy enough, imagine coming across one that also had an audio track, all of it noise? And it turns out it all encodes a file? lol, would blow people's minds. "What is this witchcraft!"

**Comment by Triden99** [comment]
>"What is this witchcraft!"

You mean like a modem audio codec?  Try piping the data through : http://www.whence.com/minimodem/

**Comment by boidushya** [comment]
I was thinking about the same thing recently, maybe try using audio using the same logic as videos in binary mode? As in sound for 1 and no sound for 0 with a minuscule interval between? Although I doubt a lot of data can be encoded this way.

**Comment by bubblefoil** [comment]
Actually I was wandering whether something like QAM used for both audio and video could improve entropy :)

**Comment by DvorakDwarf** [comment]
Adding audio would make it more data-dense but that doesn't change much since the video would just get larger and length of video is not a huge problem

**Comment by oOHiyoriOo** [comment]
Maybe it would be a nice idea to add some sort of error resistance trough audio, so instead of using it as a whole medium, as it seems it doesn't contribute to it useful anyway, use it to send some sort of checksum? or maybe some other error correction so it get#s more reliable :D
