### ISSUE TITLE
How do you handle frame sequence randomness

### ISSUE THREAD

**Issue by svobora** [DvorakDwarf/Infinite-Storage-Glitch#22]
I have quite a lot of experience with processing video as image sequence. Also coding experience as far as ffmpeg or individual codecs. When decoding a video, the video decoder e.g. inside ffmpeg can arbitrarily drop a frame based on HW, OS, or codec version. This is not noticable when watching a video, but would totally destroy this algorithm if not worked around. How do you achieve that a frame is not dropped, do you for example replicate the data in multiple frames? Or do you know a codec which assures the frame presentation order,

**Comment by DvorakDwarf** [comment]
I honestly did not know that was an issue and never had to fight against it. I used the png codec because I wanted lossless video and it worked out

**Comment by svobora** [comment]
Ah you are right, you are acting against compression of course, both space and time-based. This is why you have chosen PNG. I suppose the frame issues are only a problem in time-based compressed codecs like h264.
