### ISSUE TITLE
Could be technique for robust long-term data archival (data > video > celluloid rolls > video > data)

### ISSUE THREAD

**Issue by twardoch** [DvorakDwarf/Infinite-Storage-Glitch#25]
If this technique is robust, this could be proposed as a method for long-term data archiving. This method could theoretically allow: 

- To convert an arbitrary data file into a "video"
- Optically print that video into celluloid rolls
- Once the rolls are scanned back in, the method could be used to decode that back into the original data

So, this may have utility beyond the "YouTube glitch".

**Comment by danya02** [comment]
This is already done: the GitHub Arctic Code Vault program made a backup of all the public repos and put them on tape using [QR-code looking patterns](https://youtube.com/watch?v=fzI9FNjXQ0o), along with the human-readable instructions for how to use it.

It's probably not a good idea to use this in its current state for this though, with the lack of error-correction, versioning or most of any form of metadata.
