### ISSUE TITLE
Similarity to Data2QR

### ISSUE THREAD

**Issue by Myzel394** [DvorakDwarf/Infinite-Storage-Glitch#26]
Hey I just found out about this project and found it funny how it is a bit similar to a project I made back in a while (https://github.com/Myzel394/DataToQR). 

We both had the idea to use Google's unlimited video storage functionality to store data in a different format to get unlimited storage :D

However, I think your project is far better as it uses Rust and transforms the input way better than mine project does.

**Comment by DvorakDwarf** [comment]
Nice. I had not actually thought of this being related to QR codes before release

**Comment by Zentrom** [comment]
This "youtube storage" concept was also developed in the past, although they're less detailed than ISG:
https://github.com/lewangdev/youtube-drive - Made with Python, uses big colored squares, compression is probably worse than yours.

https://github.com/dzhang314/YouTubeDrive - Probably the first guy that did something like this.

I also plan to try doing something similar in C++ and check if GPU parallelization could speed things up or not. As i looked through the code, it seems that ISG uses the CPU mostly. (OpenCV might use the GPU though, when you call VideoWrite(), i'm not sure).

**Comment by DvorakDwarf** [comment]
The first link is a python port of the second and video size was humongous in both
