### ISSUE TITLE
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero'

### ISSUE THREAD

**Issue by stevebanik** [DvorakDwarf/Infinite-Storage-Glitch#27]
> Pick what you want to do with the program Dislodge
> What is the path to your video ? output [DcdKfmpmPwA].mp4
> Where should the output go ? test.zip
Dislodging frame ended in 17ms
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', src/embedsource.rs:47:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dislodging frame ended in 54ms

I am wondering if this is because I did not give YT enough time to render SD/HD?

**Comment by stevebanik** [comment]
% uname -a
Darwin foo 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000 arm64

**Comment by DvorakDwarf** [comment]
> I am wondering if this is because I did not give YT enough time to render SD/HD?
It might be, have you tried again after it stopped rendering ? What settings did you use ?

**Comment by DvorakDwarf** [comment]
Try updating, I made it fall back to what should be a widely used codec
