### ISSUE TITLE
Could not find encoder for codec id 62: Encoder not found

### ISSUE THREAD

**Issue by lost22git** [DvorakDwarf/Infinite-Storage-Glitch#28]
### output message when `Embed`

Could not find encoder for codec id 62: Encoder not found
Video embedded succesfully at output.avi
Etching video ended in 4247ms

**Comment by lost22git** [comment]
![isg_error](https://user-images.githubusercontent.com/65008815/220787797-69bd4892-603b-4208-90c9-39a9444a20e1.gif)

**Comment by AbdelAzizMohamedMousa** [comment]
> ### output message when `Embed`
> Could not find encoder for codec id 62: Encoder not found Video embedded succesfully at output.avi Etching video ended in 4247ms
It seems that you are working with a video encoding/decoding software or library and encountered an error message "Could not find encoder for codec id 62: Encoder not found". This error message typically indicates that the encoder for a specific video codec is missing or not properly installed in your system.

Codec id 62 refers to the H.264/MPEG-4 AVC codec, which is a widely used video codec for high-quality video compression. To resolve this error, you may need to install the H.264/MPEG-4 AVC encoder in your system. Here are some steps you can try:

Check if the encoder is installed: Verify that the H.264/MPEG-4 AVC encoder is installed in your system. You can search for the encoder in your system's software repositories or check if it is included in your video encoding/decoding library.

Install the encoder: If the encoder is not installed, you can install it manually. The installation process may vary depending on your operating system and software. You can search for installation instructions online or refer to the documentation of your video encoding/decoding library.

Update the library: If you have recently updated your video encoding/decoding library, make sure that the library is compatible with the installed encoder. You may need to update the library or install a compatible version of the encoder.

Once you have installed or updated the H.264/MPEG-4 AVC encoder, try running your software or library again and check if the error message is resolved.


> Author

**Comment by lost22git** [comment]
@AbdelAzizMohamedMousa 

how to use ffmpeg H.264/MPEG-4 AVC encoder in this app?

```shell
╰─❯ ffmpeg -v quiet -encoders | rg 264
 V....D libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V....D libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V....D h264_amf             AMD AMF H.264 Encoder (codec h264)
 V....D h264_mf              H264 via MediaFoundation (codec h264)
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)
```

**Comment by AbdelAzizMohamedMousa** [comment]
To use the H.264/MPEG-4 AVC encoder in your application using FFmpeg, you can use the libx264 encoder that is available in FFmpeg. Here are the steps to use it:

Install FFmpeg: If you haven't already, you will need to install FFmpeg on your system.

Input video: You will need to have a video that you want to encode in H.264 format. Make sure that FFmpeg is able to read the video format.

Encode the video: Once you have the video, you can use the following command to encode it using the libx264 encoder:
`ffmpeg -i input_video.mp4 -c:v libx264 -crf 23 -preset fast output_video.mp4
`

Here, -i input_video.mp4 specifies the input video file, -c:v libx264 specifies the video codec to use, -crf 23 specifies the quality level (lower is better quality but larger file size), and -preset fast specifies the encoding speed.

Output video: Once the video is encoded, you will have an output file output_video.mp4 in H.264 format that you can use in your application.

Note: The -crf option controls the quality of the output video. A lower value will result in a higher quality output but a larger file size. You can experiment with different values to find the one that works best for your needs. The -preset option controls the encoding speed. The faster the encoding, the lower the quality of the output video. Again, you can experiment with different values to find the one that works best for your needs.

**Comment by lost22git** [comment]
I don't think it's the problem caused by H264. 

Because it works after I add openh264.dll and modify forcc from png to h264.

![Screenshot 2023-02-24 040337](https://user-images.githubusercontent.com/65008815/221018561-5d96163a-ce9f-4ccf-afcb-f3e4d4cf7522.png)

![Screenshot 2023-02-24 040337-1](https://user-images.githubusercontent.com/65008815/221019063-d780bf9d-8194-4032-b08f-90208cfac50d.png)

@DvorakDwarf  Does using h264 or xvid have any impact, compared to png ?

**Comment by lost22git** [comment]
I guess fourcc png is not supported in opencv 3.4.16 ?

**Comment by lost22git** [comment]
found alloc memory error message when embed  100MB+ file😅


> thread '<unnamed>' panicked at 'Failed to create new Mat: Error { code: -4, message: "OpenCV(3.4.16) C:\\build\\3_4_winpack-build-win64-vc14\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 2764800 bytes in function 'cv::OutOfMemoryError'\n" }', src\embedsource.rs:20:14

**Comment by AbdelAzizMohamedMousa** [comment]
That's correct, the PNG FourCC codec is not supported in OpenCV 3.4.16. The FourCC code is a four-byte code that is used to identify the video codec. Although the PNG format is supported by OpenCV, it does not have a corresponding FourCC code in OpenCV 3.4.16.

However, this issue has been resolved in later versions of OpenCV, including OpenCV 4.0 and higher. In these versions, the PNG FourCC codec is supported and can be used for video encoding and decoding.

If you need to use the PNG FourCC codec in your project, you may want to consider upgrading to a later version of OpenCV.

**Comment by lost22git** [comment]
If someone wants to build windows exe

you can refer to https://gist.github.com/lost22git/338de4df49975a0596e650aa2415ef0d
