### ISSUE TITLE
Arch Linux: building executable yields libclang error and downloading+running executable yields Exec format error

### ISSUE THREAD

**Issue by vandonsel** [DvorakDwarf/Infinite-Storage-Glitch#29]
Building executable yields libclang error and downloading+running executable yields Exec format error

Build fail:
  === Using OpenCV headers from: /usr/include/opencv4
  thread 'main' panicked at 'Cannot initialize clang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/host/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.75.0/build/generator.rs:75:37
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Executable fail: 

[host@kingston ~]$ ./isg_4real.v1.0.0
-bash: ./isg_4real.v1.0.0: cannot execute binary file: Exec format error

**Comment by vandonsel** [comment]
clang is a dependency, would include in documentation

**Comment by hendkai** [comment]
Under WSL2 in Windows 11 with arch i had to install "qt"
