### ISSUE TITLE
Add encryption, as my entire nft collection is now up for grabs

### ISSUE THREAD

**Issue by Xerxes249** [DvorakDwarf/Infinite-Storage-Glitch#3]
As the videos are public everybody will be able to download my precious NFT collection. Can you please consider adding an uncrackable encryption scheme with a simple password I can easily remember or guess if I forget it.

**Comment by StellaSmith** [comment]
> As the videos are public everybody will be able to download my precious NFT collection. Can you please consider adding an uncrackable encryption scheme with a simple password I can easily remember or guess if I forget it.

You can use OpenGPG to encrypt the files before uploading, and then use it again to decrypt them.

**Comment by DvorakDwarf** [comment]
Bro just put a password on your zip archive
