### ISSUE TITLE
How i just run this a executable

### ISSUE THREAD

**Issue by JonDev2023** [DvorakDwarf/Infinite-Storage-Glitch#30]

**Comment by 53142** [comment]
I think you have to manually compile it.

**Comment by achieveordie** [comment]
@JonDev2023 If you're on Windows then you need to build it from the source, it says in the `README.md`:

> Note that the binary is not an exe file, it will not work on windows, try following the first method instead. I might add an .exe if this somehow gets popular

The steps are also provided:
> If you want to or already have went through the hassle of installing Rust, you can `git clone` this repository, then `cargo build --release`. Cd to `/target/release` directory and run the program `./isg_4real`.

Pretty simple but memory intensive as per the author.

**Comment by 53142** [comment]
There is an exe in this issue: https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/12

 Note: I did not test this exe. Please be careful when downloading executable files to prevent your computer from getting a virus.

**Comment by Shyvadi** [comment]
Exe file gets this 
![image](https://user-images.githubusercontent.com/22157510/220819638-242938cc-9861-4a98-afe2-08feef09629d.png)

**Comment by Shyvadi** [comment]
Resolved the issue by putting it directly in the opencv folder with the missing file (I suppose adding to path could work too) 
![image](https://user-images.githubusercontent.com/22157510/220819998-88540227-1e5f-4938-bbb9-838743e1bc08.png)
![image](https://user-images.githubusercontent.com/22157510/220820033-f96e8d3e-0aef-4aae-9783-0ef9590d99ed.png)

**Comment by Shyvadi** [comment]
Having another issue, 
![image](https://user-images.githubusercontent.com/22157510/220821512-1a22ffa1-4f56-4a93-b667-1811e9f302db.png)

**Comment by f1h0** [comment]
Yes, I also think that you need an exe file

**Comment by SpicyRicecaker** [comment]
> Having another issue, ![image](https://user-images.githubusercontent.com/22157510/220821512-1a22ffa1-4f56-4a93-b667-1811e9f302db.png)

I'm getting this exact same error, but I've built the executable from source on `vc16`, with the `4.7` opencv official windows binary distribution from https://opencv.org/releases/. 
![image](https://user-images.githubusercontent.com/54951411/220884983-dd5e175a-4688-47a3-bde4-ccb2a61d3dbf.png)

The output file is an empty `.avi` file. 

The issue seems to be something to do with the opencv/ffmpeg/avi api, since I tried replacing instances of `.avi` with `.mp4` in the source code and did end up with a working file.

**Comment by Leppa1** [comment]
> > Having another issue, ![image](https://user-images.githubusercontent.com/22157510/220821512-1a22ffa1-4f56-4a93-b667-1811e9f302db.png)
> 
> I'm getting this exact same error, but I've built the executable from source on `vc16`, with the `4.7` opencv official windows binary distribution from https://opencv.org/releases/. ![image](https://user-images.githubusercontent.com/54951411/220884983-dd5e175a-4688-47a3-bde4-ccb2a61d3dbf.png)
> 
> The output file is an empty `.avi` file.
> 
> The issue seems to be something to do with the opencv/ffmpeg/avi api, since I tried replacing instances of `.avi` with `.mp4` in the source code and did end up with a working file.

Same issue here. Which specific files did you change from avi to mp4? Having trouble with empty .avi file here myself.

**Comment by MeRahulAhire** [comment]
> Resolved the issue by putting it directly in the opencv folder with the missing file (I suppose adding to path could work too)

Where the path @Shyvadi?

**Comment by MeRahulAhire** [comment]
I actually wanted to know that where all the opencv .exe are located?

**Comment by 53142** [comment]
This should be helpful: https://github.com/twistedfall/opencv-rust/issues/118#issuecomment-619608278

**Comment by lost22git** [comment]
hope useful https://gist.github.com/lost22git/338de4df49975a0596e650aa2415ef0d

**Comment by Shyvadi** [comment]
> > Having another issue, ![image](https://user-images.githubusercontent.com/22157510/220821512-1a22ffa1-4f56-4a93-b667-1811e9f302db.png)
> 
> I'm getting this exact same error, but I've built the executable from source on `vc16`, with the `4.7` opencv official windows binary distribution from https://opencv.org/releases/. ![image](https://user-images.githubusercontent.com/54951411/220884983-dd5e175a-4688-47a3-bde4-ccb2a61d3dbf.png)
> 
> The output file is an empty `.avi` file.
> 
> The issue seems to be something to do with the opencv/ffmpeg/avi api, since I tried replacing instances of `.avi` with `.mp4` in the source code and did end up with a working file.

I never attempted to build the .exe myself since I was having problems. Can you post your mp4 version?
