### ISSUE TITLE
Could not open codec 'png': Unspecified error

### ISSUE THREAD

**Issue by JannikRitscher** [DvorakDwarf/Infinite-Storage-Glitch#32]
Compiled from scretch on amd64. Following error occures: 

Bytes ripped succesfully
Byte length: 311
Binary ripped succesfully
[src/etcher.rs:359] final_frame = 1
Etching frame ended in 664us
Instructions written
Etching frame ended in 1914us
Embedding thread complete!
[png @ 0x560d527d6140] Specified pixel format yuv420p is invalid or not supported
Could not open codec 'png': Unspecified error
Video embedded succesfully at output.avi
Etching video ended in 4049us

No video is created. Any help on this error?

**Comment by DvorakDwarf** [comment]
Might have something to do with the file being very small. Try to use custom settings with 144p resolution and see if it works ?

**Comment by DvorakDwarf** [comment]
Try updating, I made it fall back to what should be a widely used codec

**Comment by JannikRitscher** [comment]
First of all, thanks a lot for looking into this. 
Unfortunately the fixed made things worse for me. I updated to the new codebase, recompiled, but now I get the initial error message every time I try to embed a file. Size of the files doesn't affect this behavior. Tried many different files, ranging from 1MB, over 5MB, 20MB up to 100MB. 

Anything I can provide you with to help diagnosing this bug?

**Comment by JannikRitscher** [comment]
root@ISG:~/Infinite-Storage-Glitch/target/release# ./isg_4real 
Welcome to ISG (Infinite Storage Glitch)
This tool allows you to turn any file into a compression-resistant video that can be uploaded to YouTube for Infinite Storage:tm:

How to use:
1. Zip all the files you will be uploading
2. Use the embed option on the archive (THE VIDEO WILL BE SEVERAL TIMES LARGER THAN THE FILE, 4x in case of optimal compression resistance preset)
3. Upload the video to your YouTube channel. You probably want to keep it up as unlisted
4. Use the download option to get the video back
5. Use the dislodge option to get your files back from the downloaded video
6. PROFIT

> Pick what you want to do with the program Embed
> What is the path to your file ? /root/out/out.txt

I couldn't figure out a weird bug that happens if you set the size to something that isn't a factor of the height
If you don't want the files you put in to come out as the audio/visual equivalent of a pipe bomb, account for the above bug

> You can use one of the existing presets or custom settings Optimal compression resistance
Bytes ripped succesfully
Byte length: 36143035
Binary ripped succesfully
Etching frame ended in 581ms
Etching frame ended in 682ms
Etching frame ended in 925ms
Etching frame ended in 594ms
Etching frame ended in 1180ms
[src/etcher.rs:364] final_frame = 1255
Etching frame ended in 612us
Instructions written
Etching frame ended in 871ms
Etching frame ended in 1022ms
Etching frame ended in 920ms
Etching frame ended in 774ms

(LINES REMOVED FOR BETTER READABILITY)

Etching frame ended in 1176ms
Etching frame ended in 1273ms
Etching frame ended in 1193ms
Etching frame ended in 1181ms
Etching frame ended in 1303ms
Etching frame ended in 1523ms
Etching frame ended in 1473ms
Embedding thread complete!
Etching frame ended in 1177ms
Etching frame ended in 1384ms
Etching frame ended in 1130ms
Etching frame ended in 1324ms
Etching frame ended in 1308ms
Embedding thread complete!
Etching frame ended in 949ms
Etching frame ended in 728ms
Etching frame ended in 601ms
Etching frame ended in 660ms
Etching frame ended in 657ms
Etching frame ended in 703ms
Etching frame ended in 749ms
Etching frame ended in 842ms
Etching frame ended in 983ms
Etching frame ended in 994ms
Etching frame ended in 1074ms
Embedding thread complete!
Etching frame ended in 986ms
Etching frame ended in 841ms
Etching frame ended in 813ms
Embedding thread complete!
Etching frame ended in 542ms
Embedding thread complete!
Etching frame ended in 582ms
Embedding thread complete!
Etching frame ended in 468ms
Etching frame ended in 433ms
Embedding thread complete!
Etching frame ended in 260ms
Embedding thread complete!
[png @ 0x556f4f9a2700] Specified pixel format yuv420p is invalid or not supported
Could not open codec 'png': Unspecified error
Video embedded succesfully at output.avi
Etching video ended in 164235ms

**Comment by DvorakDwarf** [comment]
I guess your PC just doesn't have png as a codec. We'll need to find a replacement for it

**Comment by JannikRitscher** [comment]
Just to let you know, i was running debian before. 
Switched to WSL on Windows using the instructions from the newly added Dockerfile and it works just fine.
