### ISSUE TITLE
why use ISG

### ISSUE THREAD

**Issue by gans92** [DvorakDwarf/Infinite-Storage-Glitch#35]
I understand that youtube is a great way to store videos in the cloud, but why convert before uploading them?

**Comment by phadkeSharanMatrixComsec** [comment]
Because youtube only supports video file format, if the file is in some other format other than video it cannot be stored on youtube. That's why we need a converter like ISG to convert other file types to video

**Comment by zeromero-dev** [comment]
> I understand that youtube is a great way to store videos in the cloud, but why convert before uploading them?

The thing is: you can use **ANY** cloud storage for whatever files you want. You can also store encrypted videos in your cloud storage. The con to this is that most of those cloud providers has limited capacity so you **technically can't** store more than the limit.
Services that let's you upload videos like yt or vimeo or whatever you name else, are specifically designed for uploading and storing **videofiles**. As far as I know most of them has **no limits** on the amount of uploaded videos.

Hope it answers your question.
