### ISSUE TITLE
Feature suggestion: Add the ability to place 2D barcodes in the beginning of video

### ISSUE THREAD

**Issue by Lesita** [DvorakDwarf/Infinite-Storage-Glitch#38]
Suggest to add a feature for users to place an 2D barcode in the beginning of the video for data archival purposes.

**Comment by DvorakDwarf** [comment]
Explain what that would do, please

**Comment by Lesita** [comment]
> Explain what that would do, please

For most of data archives placed from backup systems are grouped into individual "Vaults" which contains a metadata with a GUID that can differ a single data archive from a particular place, for example, different archives within a single folder. As YouTube allows for file downloads for uploaded videos in a channel, it's still necessary to keep the integrity of the whole video file, in case the filename changed for some situations.

Users will be able to assign a label to the zipped folder for further use. This functionality further adds the possibility of perpending hash values to the converted video data in case a data loss happens.

**Comment by oOHiyoriOo** [comment]
So basically you want to add a barcode with Checksum to the video? i like the idea
