### ISSUE TITLE
Other streaming services , discord etc

### ISSUE THREAD

**Issue by abasgames** [DvorakDwarf/Infinite-Storage-Glitch#40]
Just wondering if its possible to support them
For example discord have support for screen sharing 
The idea is to use a virtual webcam that replay the video and the clients reads from the other end user screen

**Comment by zeromero-dev** [comment]
> Just wondering if its possible to support them For example discord have support for screen sharing The idea is to use a virtual webcam that replay the video and the clients reads from the other end user screen

You know it's up to you to make this experiment. 
The only option I see for now is the end user still needs to record the video stream anyways to decode it.
But let me know If u managed to do smth like this!
