### ISSUE TITLE
Support Storing the Files as Audio

### ISSUE THREAD

**Issue by 53142** [DvorakDwarf/Infinite-Storage-Glitch#44]
Supporting audio storage will increase the data that would be able to be stored. You should also be able to export encoded videos with encoded audio.

**Comment by benhexie** [comment]
Bruhhhh!!.... You guys are thinking in 4K XD

**Comment by 53142** [comment]
Whoops, didn't realize this is kind of a duplicate of https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/20

**Comment by zeromero-dev** [comment]
> 

Didn't realize too. Good you mentioned it.
Closing this as a duplicate of #20
