### ISSUE TITLE
Implement 360 Degree Youtube Videos

### ISSUE THREAD

**Issue by 53142** [DvorakDwarf/Infinite-Storage-Glitch#45]
Implement 360 Degree Youtube Videos? I don't know how this would work or even if it would. This would allow the storage of much more data.

**Comment by zeromero-dev** [comment]
Can you be more specific? What do you mean and can you send a video example?

**Comment by 53142** [comment]
3D Youtube videos are simply Youtube videos that are in 3D. This would allow the storage of much more data.

https://www.youtube.com/watch?v=kQ7PUUPd_g8

**Comment by zeromero-dev** [comment]
Oh you mean 360 videos. That's interesting.

**Comment by 53142** [comment]
Whoops. Forgot the name. Going to change the description.

**Comment by AndreasWintherMoen** [comment]
Would this help though? It would add more data per video second, but the size of the video file would be the same.

**Comment by 53142** [comment]
That is true...

**Comment by DvorakDwarf** [comment]
Fire idea, not very useful

**Comment by ant-7802** [comment]
literally 360 videos are the exact same as regular videos but the video creator just uses a special tool so it makes the regular video look good in 3d, same thing
