### ISSUE TITLE
Is that possible to add a password to the file?

### ISSUE THREAD

**Issue by jinfagang** [DvorakDwarf/Infinite-Storage-Glitch#54]

**Comment by YugiFanGX** [comment]
Currently only in its own. Use GNUPG or 7zip.

**Comment by jinfagang** [comment]
@YugiFanGX thank u, is that possible add pass code in youtube for this file to view?

**Comment by Threpio** [comment]
No?

A good idea would be to use unlisted videos and not share the video.

> Unfortunately, YouTube does not offer password protection or anything similar for your videos.
