### ISSUE TITLE
Windows docker requires "%cd%" instead of ${PWD}

### ISSUE THREAD

**Issue by Shyvadi** [DvorakDwarf/Infinite-Storage-Glitch#61]

**Comment by beyse** [comment]
This is interesting. Perhaps there is a difference in our Windows systems 🤔 

I have Windows 11 and I am using WSL2. In my Docker Desktop app I have Enabled WSL Integration for my Ubuntu distro. 

When I run 

```
docker run -it --rm -v ${PWD}:/home/Infinite-Storage-Glitch isg cargo build --release
```

from my PowerShell (not inside a WSL shell) it works just fine. If you share your environment, perhaps we can find why it works differently.

**Comment by Shyvadi** [comment]
> This is interesting. Perhaps there is a difference in our Windows systems 🤔
> 
> I have Windows 11 and I am using WSL2. In my Docker Desktop app I have Enabled WSL Integration for my Ubuntu distro.
> 
> When I run
> 
> ```
> docker run -it --rm -v ${PWD}:/home/Infinite-Storage-Glitch isg cargo build --release
> ```
> 
> from my PowerShell (not inside a WSL shell) it works just fine. If you share your environment, perhaps we can find why it works differently.

I use Windows 11 as well and am using Docker Desktop downloaded fresh. I am running it without any ubuntu subsystem enabled if that's what you are referring to. 

![image](https://user-images.githubusercontent.com/22157510/221332791-425a2d17-c508-4204-80ab-5c1b0cc230d3.png)
![image](https://user-images.githubusercontent.com/22157510/221332803-85b6a70b-a015-4921-ba55-c8dfda7614cc.png)

**Comment by beyse** [comment]
I guess it is probably easiest to update the readme file to point this out.

**Comment by ayhamo** [comment]
i would like to add that if you run the command from powershell, it will work, but cmd will not

**Comment by beyse** [comment]
> i would like to add that if you run the command from powershell, it will work, but cmd will not

I added it as part of #72

**Comment by beyse** [comment]
Since #72 is merged we can close this.
