### ISSUE TITLE
Multithread Support

### ISSUE THREAD

**Issue by DeEskalator** [DvorakDwarf/Infinite-Storage-Glitch#67]
I compiled it for macOS and I mean it is pretty quick, but could there be some multithread support be added to speed up things?
<img width="658" alt="Screenshot 2023-02-25 at 00 09 50" src="https://user-images.githubusercontent.com/47759580/221318707-5e0334e0-910b-4256-95a9-baed6607e2e4.png">

**Comment by DvorakDwarf** [comment]
105% Efficiency

**Comment by DeEskalator** [comment]
Found this flag in args.rs.
<img width="250" alt="Screenshot 2023-02-25 at 11 08 24" src="https://user-images.githubusercontent.com/47759580/221351304-8a6a8727-f514-4e7f-a838-b5d77640d2af.png">

How do I set it to five threads?

**Comment by foodornt** [comment]
> Found this flag in args.rs.
> 
> ```
>     /// Threads to use when encoding
>     #[arg(long)]
>     pub threads: Option<usize>,
> ```
> 
> How do I set it to five threads?

`cargo run -- embed --threads=5` I guess?
