### ISSUE TITLE
./isg_4real: error while loading shared libraries: libopencv_barcode.so.4.5d: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mkukiro** [DvorakDwarf/Infinite-Storage-Glitch#75]
I tried running `./isg_4real` on the terminal but this error popped up

**System info**

- Fedora Linux 37
- GNOME 43.2
- Wayland
- 64-bit

**Comment by wrawler** [comment]
same happened with me, so i decided to use docker and it worked

**Comment by BestRazer** [comment]
> same happened with me, so i decided to use docker and it worked

I tried that too, the error still popped up.

**Comment by mkukiro** [comment]
> same happened with me, so i decided to use docker and it worked 

I used docker in fact
