### ISSUE TITLE
Docker version of ISG Download video error 

### ISSUE THREAD

**Issue by PR0M3TH3AN** [DvorakDwarf/Infinite-Storage-Glitch#76]
Im getting this error when trying to download an unlisted encoded video. 

Starting the download, there is no progress bar
Error: io error: Text file busy (os error 26)

Caused by:
    Text file busy (os error 26)
PS C:\Users\Adam\Documents\GitHub\Infinite-Storage-Glitch>

**Comment by PR0M3TH3AN** [comment]
it also creates a strange file in the root dir called "yt-dlp"

**Comment by DvorakDwarf** [comment]
Try updating
