### ISSUE TITLE
The precompiled executable is ARM?

### ISSUE THREAD

**Issue by LZ2DMV** [DvorakDwarf/Infinite-Storage-Glitch#8]
Am i missing something here or the provided executable is arm64 instead of x86_64?

```
$ ./isg_4real.v1.0.0
bash: ./isg_4real.v1.0.0: cannot execute binary file: Exec format error

$ file isg_4real.v1.0.0
isg_4real.v1.0.0: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>

$ uname -m
x86_64
```

**Comment by zeromero-dev** [comment]
Yeah, that's probably why you can't run this.
Should be reuploaded with 2 versions: ARM and nonARM.
For now, just build it from the source, it works!

**Comment by Kovinda** [comment]
> 



> Am i missing something here or the provided executable is arm64 instead of x86_64?
> 
> ```
> $ ./isg_4real.v1.0.0
> bash: ./isg_4real.v1.0.0: cannot execute binary file: Exec format error
> 
> $ file isg_4real.v1.0.0
> isg_4real.v1.0.0: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
> 
> $ uname -m
> x86_64
> ```

Check #12
