### ISSUE TITLE
Auto detection of the file name and extension would be helpful

### ISSUE THREAD

**Issue by MeRahulAhire** [DvorakDwarf/Infinite-Storage-Glitch#80]
Hi @DvorakDwarf, really loved your project and I was just trying this out. One thing I particularly noticed was that during dislodging it asks what the name of file and extension is. 

It would be more helpful if the filename and extension were directly encoded inside of the video. 
Because we human tend to forget things and if we don't know the file name and its type, we essentially cannot restore our file.

**Comment by pixelomer** [comment]
Not that this is a bad idea, but you could use [`file`](https://linux.die.net/man/1/file) to detect the file type after extracting it.

**Comment by MeRahulAhire** [comment]
As an end user who isn't a dev that would be utmost helpful as this project grows.
